### PR TITLE
added cba recommendation to overall HC

### PR DESCRIPTION
**Pull request by KwamiS**
The changes on this branch add a consolidated recommendation of samples and corresponding penetration levels to consider for cost-benefit analysis studies.

### CODE REVIEW

**Review by wenbowangnrel — COMMENTED** [review]
Is there for screening samples or scenarios?

**Comment by KwamiS** [comment]
> 

It unifies the metric level recommendations and explicitly gives the list of penetration levels for each sample recommended.

**Comment by wenbowangnrel** [comment]
> 

sounds good

**Review by wenbowangnrel — APPROVED** [review]

**Review by jgu2 — APPROVED** [review]
It looks good to me. I re-format the code a bit.

**Review by daniel-thom — APPROVED** [review]

**Pull request merged**
